blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostList.as_view(), name='post-list'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post-detail'),
]

exchange/urls.py
from django.urls import path

from exchange import views

app_name = 'exchange'
urlpatterns = [
    path('', views.ExchangeRateOverview.as_view(), name='overview'),
    path('<slug:slug>/', views.CurrencyDetail.as_view(), name='currency_detail'),
]

fxrate/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from fxrate.views import Homepage

urlpatterns = i18n_patterns(
    path('blog/', include('blog.urls')),
    path('exchange/', include('exchange.urls')),
    path('', Homepage.as_view(), name="homepage"),
    path('admin/', admin.site.urls),
    prefix_default_language=False
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts') # Das Löschen muss getestet werden.
    short_description = models.TextField(max_length=150)
    content = models.TextField()
    img = models.ImageField()
    category = models.CharField(max_length=50)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, )

    class Meta:
        ordering = ['creation_date']

    def __str__(self):
        return self.title

exchange/models.py
from django.db import models
from datetime import date


class Currency(models.Model):
    country = models.CharField(max_length=50, unique=True)
    iso = models.CharField(max_length=5, unique=True)
    designation = models.CharField(max_length=5, null=True)
    symbol = models.CharField(max_length=5, null=True)
    flag = models.CharField(max_length=1, null=True)

    def __str__(self):
        return "Currency of -- {} -- {}".format(self.country,  self.iso)


class ExchangeRate(models.Model):
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, related_name='currency')
    buy = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    sell = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_date_time = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return "Exchange rate of -- {} -- on date: {}".format(self.currency.iso, str(self.change_date_time))

    @property
    def is_today(self):
        return date.today() == self.change_date_time.date()

blog/views.py
from django.views.generic import DetailView, ListView
from blog.models import Post


class PostDetail(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class PostList(ListView):
    queryset = Post.objects.all()
    template_name = 'blog/post_list.html'

exchange/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.functions import Coalesce
from django.views.generic import ListView

from exchange.models import ExchangeRate, Currency


class CurrencyDetail(ListView):
    exchange_rates = ExchangeRate
    currencies = Currency
    template_name = 'exchange/currency_detail.html'

    def get_queryset(self):
        return self.exchange_rates.objects.all()\
            .filter(currency__iso=self.kwargs['slug'].upper())\
            .order_by('-change_date_time')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['currency'] = self.currencies.objects.get(iso=self.kwargs['slug'].upper())
        except Currency.DoesNotExist:
            context['currency'] = None
        finally:
            context['slug'] = self.kwargs['slug'].upper()
            return context


class ExchangeRateOverview(ListView):
    # finds the latest exchange rate row for each currency
    # TODO: Disable caching
    # TODO: Find django method instead of SQL query
    queryset = ExchangeRate.objects.raw('''SELECT c.*, e1.*
    FROM exchange_currency c
    JOIN exchange_exchangerate e1 ON (c.id = e1.currency_id)
    LEFT OUTER JOIN exchange_exchangerate e2 ON (c.id = e2.currency_id AND
        (e1.change_date_time < e2.change_date_time OR (e1.change_date_time = e2.change_date_time AND e1.id < e2.id)))
    WHERE e2.id IS NULL''')

    template_name = 'exchange/overview.html'

fxrate/views.py
from django.shortcuts import redirect
from django.views.generic import ListView

from blog.models import Post
from exchange.models import ExchangeRate


class Homepage(ListView):
    queryset = Post.objects.filter(status=1).order_by('creation_date')[:2]
    template_name = 'homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['exchangerate_list'] = ExchangeRate.objects.raw('''SELECT c.*, e1.*
    FROM exchange_currency c
    JOIN exchange_exchangerate e1 ON (c.id = e1.currency_id)
    LEFT OUTER JOIN exchange_exchangerate e2 ON (c.id = e2.currency_id AND
        (e1.change_date_time < e2.change_date_time OR (e1.change_date_time = e2.change_date_time AND e1.id < e2.id)))
    WHERE e2.id IS NULL''')
        return context

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <div class="row">
        <div class="col card mb-3">
            <div class="card-body">
                <h1 class="my-3">{% block title %} {{ object.title }} {% endblock title %}</h1>
                <p class=" text-muted"> {% trans 'writen by' %} {{ post.author }} | {{ post.creation_date|date:"H:i, d-m-Y" }}</p>
                <p class="card-text ">{{ object.content | safe }}</p>
                {% lorem 3 p random %}
            </div>
        </div>
    </div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <!-- Blog Cards -->

    <h2>{% trans 'All News' %}</h2><hr>
    <div class="row mb-5">
    {% for post in post_list %}
    <div class="col-md-6">
        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
              <div class="col p-4 d-flex flex-column position-static">
                <div class="float-right">
                  <strong class="d-inline-block mb-2 text-primary">{{ post.title }}</strong>
                  <p class="card-text mb-auto">{{ post.short_description }}</p>
                  <a href="{% url 'blog:post-detail' post.slug %}" class="stretched-link">{% trans 'Continue reading' %}</a>
                  <div class="mb-1 text-muted">{{ post.edit_date|date:"H:i, d-m-Y" }}</div>
                 </div>
              </div>
              <div class="col-auto d-none d-lg-block">
                <img src="{{ post.img.url }}"  width="200" height="250">
              </div>
        </div>
    </div>
    {% endfor %}
    </div>

    <!-- Featured Article -->
    <main class="mb-5">
        <h2>Featured</h2><hr>
        {% lorem 7 p random %}
    </main>

{% endblock content %}

exchange/templates/exchange/currency_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="mb-5">
    <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown link
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </div>

    <section class="page-section" id="services">
        <div class="container p-3 my-3 border rounded-lg">
            <h2 class="text-center mt-0">{{ currency.designation}} {{ currency.flag}}</h2>
             <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <h3 class="h4 mb-2">{% trans 'Actual rate' %}</h3>
                        <p class="text-muted mb-0">!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <h3 class="h4 mb-2">{% trans 'High' %}</h3>
                        <p class="text-muted mb-0">.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <i class="fas fa-4x fa-globe text-primary mb-4"></i>
                        <h3 class="h4 mb-2"> {% trans 'low' %}</h3>
                        <p class="text-muted mb-0">!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <h3 class="h4 mb-2">{% trans 'Actual rate' %}</h3>
                        <p class="text-muted mb-0">?</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% if currency %}
        <ul class="list-inline">
            <li class="list-inline-item "><span class="h4"> {{ currency.country}} {{ currency.flag}}</span></li>
            <li class="list-inline-item float-right"><span class="h4">{{ currency.symbol}} {% trans 'All rate updates' %} {{ currency.designation}} </span></li>
        </ul>
    {% else %}
        <h2>Währung nicht gefunden: {{ slug }}</h2><hr>
    {% endif %}

    {% if exchangerate_list %}
    <table class="table table-hover table-striped table-bordered w-100">

        <thead>
            <tr class="table-primary">
                <th>{% trans 'Sell' %}</th>
                <th>{% trans 'Buy' %}</th>
                <th class="d-none d-sm-table-cell">{% trans 'Date' %}</th>
            </tr>
        </thead>

        <tbody>
            {% for exchangerate in exchangerate_list  %}
            <tr>
                <td>{{ exchangerate.sell }}</td>
                <td>{{ exchangerate.buy }}</td>
                <td class="d-none d-sm-table-cell">
                    {% if exchangerate.is_today %}
                        {% trans 'Today' %}, {{ exchangerate.change_date_time|date:"H:i:s"}}
                    {% else %}
                        {{ exchangerate.change_date_time }}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
    {% else %}
        <div class="jumbotron">
            <h4>Keine Daten gefunden</h4><hr>
            <a href="{% url 'exchange:overview' %}">Zurück zur Übersicht</a>
        </div>
    {% endif %}

</div>

{% endblock content %}

exchange/templates/exchange/overview.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="mb-5">


    <h2>{% trans 'Exchange Rates' %}</h2>
    <table class="table table-hover table-striped table-bordered w-100">
        <thead>
        <tr>
            <th>🏳️</th>
{#            <th class="d-none d-sm-table-cell">&#x00A4</th>#}
            <th class="d-none d-sm-table-cell">{% trans 'Currency' %}&#x00A4</th>
            <th class="d-table-cell d-sm-none">ISO</th>
            <th>{% trans 'Sell' %}</th>
            <th>{% trans 'Buy' %}</th>
            <th class="d-none d-sm-table-cell">{% trans 'Date' %}</th>

        </tr>
        </thead>
        <tbody>
        {% for exchangerate in exchangerate_list  %}
        <tr onclick="window.location='{% url 'exchange:currency_detail' exchangerate.currency.iso %}'">
            <td style="width: 1em">{{ exchangerate.currency.flag }}</td>
{#            <td class="D-NONE d-sm-table-cell" >{{ exchangerate.currency.symbol }}</td>#}
            <td class="d-none d-sm-table-cell">{{ exchangerate.currency.designation }} {{ exchangerate.currency.symbol }}</td>
            <td class="d-table-cell d-sm-none">{{ exchangerate.currency.iso }} {{ exchangerate.currency.symbol }}</td>
            <td>{{ exchangerate.sell }}</td>
            <td>{{ exchangerate.buy }}</td>
            <td class="d-none d-sm-table-cell">
                {% if exchangerate.is_today %}
                    {% trans 'Today' %}, {{ exchangerate.change_date_time|date:"H:i:s"}}
                {% else %}
                    {{ exchangerate.change_date_time }}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="fa">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

         <!-- style -->
        <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/base.css" %}" rel="stylesheet">
        <link href="{% static "css/header.css" %}" rel="stylesheet">
        <link href="{% static "css/footer.css" %}" rel="stylesheet">
        {% block stylesheets %}{% endblock %}

        <!-- javascript -->
        <script src="{% static "bootstrap/jQuery/jquery-3.4.1.min.js" %}"></script>
        <script type="text/javascript" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
        {% block javascript %}{% endblock %}

        <!-- title and tap icon -->
        <title>{% block title %}{% trans 'Financial Market' %}{% endblock %}</title>
        {#<link rel="shortcut icon" type="image/x-icon" href="{% static "img/favicon.ico" %}" sizes="16x16 32x32 48x48 64x64">#}

    </head>


    {% block body %}<body>

    <!-- header part-->
    {% block header %}
          <header>
          </header>
    {% endblock %}


    <!-- nav part-->
    {% block nav %}

        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-orange border-bottom box-shadow">
    
            <a class="text-dark" href="{% url 'homepage' %}"><img src="{% static 'img/logo.svg' %}" height="40px" class="mr-3"></a>
            <a class="text-dark mr-md-auto font-times nounderline" href="{% url 'homepage' %}"><h1 class="my-0 ">{% trans 'Financial Market' %}</h1></a>
            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark" href="{% url 'homepage' %}">{% trans 'Home' %}</a>
                <a class="p-2 text-dark" href="{% url 'blog:post-list' %}">{% trans 'News' %}</a>
                <a class="p-2 text-dark" href="{% url 'exchange:overview' %}">{% trans 'Exchange Table' %}</a>
            </nav>
         </div>

    {% endblock %}

    <div class="container pt-5">

{#    <ul class="nav justify-content-center mb-3">#}
{#        <li class="nav-item badge-pill badge-success m-2">#}
{#            <a class="nav-link text-white" href="#">Cool</a>#}
{#        </li>#}
{#        <li class="nav-item badge-pill badge-primary m-2">#}
{#            <a class="nav-link text-white" href="#">News</a>#}
{#        </li>#}
{#        <li class="nav-item badge-pill badge-info m-2">#}
{#            <a class="nav-link text-white" href="#">Trend</a>#}
{#        </li>#}
{#        <li class="nav-item badge-pill badge-danger m-2">#}
{#            <a class="nav-link text-white" href="#">Financial</a>#}
{#        </li>#}
{#    </ul>#}

    <!-- main part-->
    {% block content %}{% endblock %}

    </div>

        <!-- footer part-->
    {% block footer %}
        <footer class="blog-footer">

            <div class="small">Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

            <ul class="nav justify-content-center m-2">
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">{% trans 'About' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">{% trans 'Contact' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">{% trans 'Terms' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="#">{% trans 'Cookies' %}</a>
                </li>
            </ul>
            <p><a href="#">{% trans 'Back to top' %}</a></p>
        </footer>
    {% endblock %}

    </body>{% endblock %}
</html>

templates/homepage.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block stylesheets %}<link href="{% static "css/homepage.css" %}" rel="stylesheet">{% endblock %}
{% block content %}

    <!-- Tabels -->
<div class="mb-5">
    <h2>{% trans 'Exchange Rates' %}</h2>
    <table class="table table-hover table-striped table-bordered w-100">
        <thead>
            <tr>
                <th>🏳️</th>
                <th class="d-none d-sm-table-cell">{% trans 'Currency' %}&#x00A4</th>
                <th class="d-table-cell d-sm-none">ISO</th>
                <th>{% trans 'Sell' %}</th>
                <th>{% trans 'Buy' %}</th>
                <th class="d-none d-sm-table-cell">{% trans 'Date' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for exchangerate in exchangerate_list  %}
            <tr onclick="window.location='{% url 'exchange:currency_detail' exchangerate.currency.iso %}'">
                <td style="width: 1em">{{ exchangerate.currency.flag }}</td>
                <td class="d-none d-sm-table-cell">{{ exchangerate.currency.designation }} {{ exchangerate.currency.symbol }}</td>
                <td class="d-table-cell d-sm-none">{{ exchangerate.currency.iso }} {{ exchangerate.currency.symbol }}</td>
                <td>{{ exchangerate.sell }}</td>
                <td>{{ exchangerate.buy }}</td>
                <td class="d-none d-sm-table-cell">
                    {% if exchangerate.is_today %}
                        {% trans 'Today' %}, {{ exchangerate.change_date_time|date:"H:i:s"}}
                    {% else %}
                        {{ exchangerate.change_date_time|date:"H:i, d-m-Y" }}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>


    <!-- Blog Cards -->

    <h2>{% trans 'News' %}</h2><hr>
    <div class="row mb-5">
    {% for post in post_list %}
    <div class="col-md-6">
        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
              <div class="col p-4 d-flex flex-column position-static">
                <div class="float-right">
                  <strong class="d-inline-block mb-2 text-primary">{{ post.title }}</strong>
                  <p class="card-text mb-auto">{{ post.short_description }}</p>
                  <a href="{% url 'blog:post-detail' post.slug %}" class="stretched-link"> {% trans 'Continue reading' %} </a>
                  <div class="mb-1 text-muted">{{ post.edit_date|date:"H:i, d-m-Y" }}</div>
                 </div>
              </div>
              <div class="col-auto d-none d-lg-block">
                <img src="{{ post.img.url }}"  width="200" height="250">
              </div>
        </div>
    </div>
    {% endfor %}
    </div>

    <div class="row">

        <!-- Featured Article -->
        <main class="col-lg-8 mb-5">
            <h2>Featured</h2><hr>
            {% lorem 7 p random %}
        </main>

        <!-- Featured Article -->
        <aside class="col-lg-4">
            <div class="jumbotron">
                <h1 class="my-5">Werbung</h1>
                {% lorem 1 p random %}
            </div>
            <div class="jumbotron">
                <h1 class="my-5">Werbung</h1>
                {% lorem 1 p random %}
            </div>
        </aside>
    </div>
{% endblock %}